news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /

auth:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
