<?php

namespace RomaChe\NewsBundle\Repository;

/**
 * ChmodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChmodRepository extends \Doctrine\ORM\EntityRepository
{
}
