auth_homepage:
    path:     /
    defaults: { _controller: AuthBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: AuthBundle:Login:login }

logout:
    path:     /logout
    defaults: { _controller: AuthBundle:Login:logout }
