staff_super:
    path:     /super
    defaults: { _controller: AuthBundle:Default:index }
staff_admin:
    path:     /admin
    defaults: { _controller: AuthBundle:Default:index }
staff_publisher:
    path:     /publisher
    defaults: { _controller: AuthBundle:Default:index }
staff_writer:
    path:     /writer
    defaults: { _controller: AuthBundle:Default:index }



checkAddingRole:
    path:     /checkAddingRole
    defaults: { _controller: AuthBundle:Staff:checkAddingRole }
getUsersList:
    path:     /getUsersList
    defaults: { _controller: AuthBundle:Staff:getUsersList }
getUser:
    path:     /getUser
    defaults: { _controller: AuthBundle:Staff:getUser }
updateRoles:
    path:     /updateRoles
    defaults: { _controller: AuthBundle:Staff:updateRoles }
